### ISSUE TITLE
BrainJS is no longer maintained

### ISSUE THREAD

**Issue by nemo** [mysamai/natural-brain#2]
Hey,

We were using this classifier in our system and since BrainJS is no longer maintained, we ended up writing up the exact same thing using the synaptic package.

If you want to check it out, [here it is](https://github.com/nemo/natural-synaptic).

**Comment by daffl** [comment]
I saw that BrainJS isn't officially maintained anymore but it was working really well for this case and it is still probably the most user-friendly. I wanted to have a look at Synaptic too though and will check out your connector to see how it behaves with https://github.com/daffl/mysam.

**Comment by nemo** [comment]
Yeah, I actually ran across this project through your mysam video :)

Essentially, I've tried to replicate the BrainJS's neural network with Synaptic. The same tests are passing just fine as well (and our MSE is actually lower now with this new setup) so would love to hear if you're getting better/same results!

**Comment by daffl** [comment]
That sounds great, I'll definitely give it a try.

**Comment by ohenepee** [comment]
Please GET THIS REPO BACK UP.... The community-backed BrainJS is UP and DOINg GREAT so far... I hope this doesn't take long to see an update on NPM

https://github.com/harthur-org/brain.js
