### ISSUE TITLE
How can I return the value of classification ?

### ISSUE THREAD

**Issue by Cristianexr** [mysamai/natural-brain#30]
var BrainJSClassifier = require('natural-brain');
var classifier = new BrainJSClassifier();

classifier.addDocument('my unit-tests failed.', 'software');
classifier.addDocument('tried the program, but it was buggy.', 'software');
classifier.addDocument('tomorrow we will do standup.', 'meeting');
classifier.addDocument('the drive has a 2TB capacity.', 'hardware');
classifier.addDocument('i need a new power supply.', 'hardware');
classifier.addDocument('can you play some new music?', 'music');

classifier.train();

////////SERVER METHOD

'sendToServer':function(message){
      var classification = classifier.classify(message);
      console.log(classification);  //=> print classificaiton
      return classification;  //=> return undefined
    }

**Comment by daffl** [comment]
`classifier.getClassifications(message)` will return an object with all classifications.

**Comment by Cristianexr** [comment]
nope
![screenshot from 2017-11-29 20-56-48](https://user-images.githubusercontent.com/16765980/33393434-dec8c5a0-d547-11e7-8be1-a24080931821.png)

**Comment by Cristianexr** [comment]
Hmm, I think I solve it by doing in another way. Thank you anyway.

**Comment by daffl** [comment]
I'm using this right in https://github.com/mysamai/mysam/blob/master/lib/services/classify/classify.class.js#L40
