### ISSUE TITLE
I can't run the app

### ISSUE THREAD

**Issue by some81** [mysamai/natural-brain#46]
Hi, 
I clone the repo and did npm install, but then I do npm start I got this:
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'compile' ]
2 info using npm@6.4.1
3 info using node@v8.5.0
4 verbose stack Error: missing script: compile
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:514:3)
5 verbose cwd /Users/atodorov/Desktop/Work/natural-brain
6 verbose Darwin 16.7.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
8 verbose node v8.5.0
9 verbose npm  v6.4.1
10 error missing script: compile
11 verbose exit [ 1, true ]`

**Comment by daffl** [comment]
This is a module only and does not need to be run. Looks like the start script is a leftover from a previous version.
